version: '2'
# Creates New Accounts In ./keystore
# First Create ./password.txt With Your Secret Passphrase
# Scale to the Desired Number of Accounts
# Run with: docker-compose -f addToKeystore.yml up --scale accounts=3

services:
  accounts:
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile.preBuilt
    env_file: .env
    volumes: # Volume in the Password File
      - ./password.txt:/password.txt
      - ./keystore/:/root/.ethereum/keystore
    entrypoint: geth account new  --password /password.txt
  