version: '2'

# geth Private Network
# Start with: docker-compose up -d

services:
  bootnode:
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile
    image: geth-private-net
    ports:
      - "8545:8545"
    env_file: .env
    # volumes:
      # - ./keystore/:/root/.ethereum/keystore
    networks:
      geth-private:
        ipv4_address: 172.19.0.2
    entrypoint:
      - ash
      - -c
      - |
          geth \
          --nodekeyhex $$BOOTNODE_KEY_HEX \
          --networkid $$NETWORK_ID \
          --password /private-net/files/password.txt \
          --unlock $$UNLOCKED_ACCOUNTS \
          --etherbase $$ETHERBASE \
          --rpc \
          --rpcport 8545 \
          --rpcaddr 0.0.0.0 \
          --rpccorsdomain "*" \
          --mine \
          --minerthreads=1
  node:
    image: geth-private-net
    depends_on:
      - bootnode
    ports:
      - "8545"
    env_file: .env
    networks:
      geth-private:
    entrypoint:
      - ash
      - -c
      - |
          geth \
          --fast \
          --nodekeyhex $$NODE_KEY_HEX \
          --networkid $$NETWORK_ID \
          --password /private-net/files/password.txt \
          --unlock $$UNLOCKED_ACCOUNTS \
          --etherbase $$ETHERBASE \
          --rpc \
          --rpcport 8545 \
          --rpcaddr 0.0.0.0 \
          --rpccorsdomain "*"

networks:
  geth-private:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1

# For Reference:
# BOOTNODE_IP=$$(dig +short bootnode)
# --bootnodes=enode://$$BOOTNODE_ENODE@172.19.0.2:3030 \
