version: '2'

# geth Private Network
# Start with: docker-compose up -d

services:
  bootnode:
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile
    image: geth-private-net
    ports:
      - "8545:8545"
    env_file: .env
    networks:
      geth-private:
        # Hard Code Port for Static Node Connection
        ipv4_address: 172.19.0.2
    command: --nodekeyhex $BOOTNODE_KEY_HEX 
  miner:
    depends_on: 
      - bootnode
    image: geth-private-net
    ports:
      - "8545"
    env_file: .env
    networks:
      geth-private:
    command: --mine --minerthreads=1 --etherbase $ETHERBASE
  # Uncomment node if you want scale, i.e. docker-compose up --scale node=5  
  # node:
  #   depends_on:
  #     - bootnode
  #   image: geth-private-net
  #   ports:
  #     - "8545"
  #   env_file: .env
  #   networks:
  #     geth-private:
         

networks:
  geth-private:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
