version: '2'

# geth Private Network
# Start with: docker-compose up -d

networks:
  geth-private:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/24
         gateway: 10.10.10.1
         
services:
  bootnode: # Cannot be Scaled
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile.gethPreBuilt
    image: geth-private-net
    ports:
      - "8545:8545"
    env_file: .env
    networks:
      geth-private:
        # Hard Coded IP for Static Node Connection
        ipv4_address: 10.10.10.10
    volumes: # Volume in Persistence, Password File and Keystore
      # - ./persistent/bootnode:/root/.ethereum
      - ./keystore:/root/.ethereum/keystore
      - ./password.txt:/password.txt:ro
    command: >
      --verbosity 6
      --nodekeyhex $BOOTNODE_KEY_HEX 
      --unlock $UNLOCKED_ACCOUNTS 
      --password /password.txt
      --mine 
      --minerthreads=1 
      --etherbase $ETHERBASE
  # Uncomment the Following to Add More Miners
  # You May Want to Remove the Minig Flags from the Bootnode
  # miner: # Can be Scaled: docker-compose up --scale miner=5
  #   depends_on: 
  #     - bootnode
  #   image: geth-private-net
  #   env_file: .env
  #   networks:
  #     geth-private:
  #   volumes: # Volume in Persistence and static-nodes.json
  #     # - ./persistent/miner:/root/.ethereum
  #     - ./files/static-nodes.json:/root/.ethereum/geth/static-nodes.json:ro
  #   command: >
  #     --mine 
  #     --minerthreads=1 
  #     --etherbase $ETHERBASE
  # Uncomment the Following to Add More Nodes
  # node: # Can be Scaled: docker-compose up --scale node=5
  #   depends_on:
  #     - bootnode
  #   image: geth-private-net
  #   ports: # expose RPC on Dynamoc Port
  #     - "8545"
  #   env_file: .env
  #   networks:
  #     geth-private:
  #   volumes: # Volume in static-nodes.json
  #     - ./files/static-nodes.json:/root/.ethereum/geth/static-nodes.json:ro
