# Pull Geth into a second stage deploy alpine container
FROM ethereum/client-go

# Private Network Files
COPY ./private-net/files/ /private-net/files/
COPY ./private-net/scripts/ /private-net/scripts/
COPY ./private-net/keystore /root/.ethereum/keystore

RUN geth init /private-net/files/genesis.json

ENTRYPOINT ["/private-net/files/entrypoint.sh"]