version: '2'

# geth Private Network
# Start with: docker-compose up -d

networks:
  geth-private:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/24
         gateway: 10.10.10.1
         
services:
  bootnode: # Cannot be Scaled
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile
    image: geth-private-net
    ports:
      - "8545:8545"
    env_file: .env
    networks:
      geth-private:
        # Hard Coded IP for Static Node Connection
        ipv4_address: 10.10.10.10
    volumes: # Volume in the Password File and Keystore
      # - ./bootnode:/root/.ethereum
      - ./password.txt:/password.txt:ro
      - ./keystore:/root/.ethereum/keystore
    command: >
      --nodekeyhex $BOOTNODE_KEY_HEX 
      --unlock $UNLOCKED_ACCOUNTS 
      --password /password.txt
      --nodiscover
      --verbosity 6
  miner: # Can be Scaled: docker-compose up --scale miner=5
    depends_on: 
      - bootnode
    image: geth-private-net
    env_file: .env
    networks:
      geth-private:
    volumes:
      # - ./miner:/root/.ethereum
      - ./files/static-nodes.json:/root/.ethereum/geth/static-nodes.json:ro
    command: >
      --mine 
      --minerthreads=1 
      --etherbase $ETHERBASE
  # Uncomment the Following to Add More Nodes
  # node: # Can be Scaled: docker-compose up --scale node=5
  #   depends_on:
  #     - bootnode
  #   image: geth-private-net
  #   ports:
  #     - "8545"
  #   env_file: .env
  #   networks:
  #     geth-private:
  #   volumes:
  #     - ./files/static-nodes.json:/root/.ethereum/geth/static-nodes.json:ro
