version: '2'

# geth Private Network
# Start with: docker-compose up -d

services:
  bootnode:
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile
    image: geth
    ports:
      - "30301/udp"
    env_file: .env
    entrypoint:
      - ash
      - -c
      - bootnode --nodekeyhex $$NODE_KEY_HEX
  miner:
    image: geth
    depends_on:
      - bootnode
    env_file: .env
    entrypoint:
      - ash
      - -c
      - |
          IP=$$(dig +short bootnode)
          geth \          
          --bootnodes=enode://$$BOOTNODE_ENODE@$$(dig +short bootnode):3031 \
          --networkid $$NETWORK_ID \
          --rpcaddr 0.0.0.0 \
          --mine \
          --minerthreads=1 \
          --etherbase=$${MINER_ETHERBASE}
  node:
    image: geth
    depends_on:
      - bootnode
    ports:
      - "8545"
    env_file: .env
    volumes:
      - ./keystore/:/root/.ethereum/keystore
    entrypoint:
      - ash
      - -c
      - |
          geth \
          --bootnodes=enode://$$BOOTNODE_ENODE@$$(dig +short bootnode):3031 \
          --networkid $$NETWORK_ID \
          --password /private-net/files/password.txt \
          --unlock "$${UNLOCKED_ACCOUNTS}" \
          --rpc \
          --rpcport 8545 \
          --rpcaddr 0.0.0.0 \
          --rpccorsdomain "*"