version: '2'

# geth Private Network
# Start with: docker-compose up -d

services:
#   bootnode:
#     build: 
#       context: ..
#       dockerfile: ./private-net/Dockerfile
#     image: geth-private-net
#     ports:
#       - "30301/udp"
#     env_file: .env
#     entrypoint:
#       - ash
#       - -c
#       - bootnode --nodekeyhex $$BOOTNODE_KEY_HEX
  bootnode:
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile
    image: geth-private-net
    ports:
      - "8545"
    env_file: .env
    entrypoint:
      - ash
      - -c
      - |
          IP=$$(dig +short bootnode)
          geth \
          --fast \
          --nodekeyhex $$MINER_KEY_HEX \
          --networkid $$NETWORK_ID \
          --bootnodes=enode://$$BOOTNODE_ENODE@$$IP:3031 \
          --password /private-net/files/password.txt \
          --unlock $$UNLOCKED_ACCOUNTS \
          --etherbase 0 \
          --rpc \
          --rpcport 8545 \
          --rpcaddr 0.0.0.0 \
          --rpccorsdomain "*" \
          --mine \
          --minerthreads=1
  node:
    image: geth-private-net
    depends_on:
      - bootnode
    ports:
      - "8545"
    env_file: .env
    # volumes:
    #   - ./keystore/:/root/.ethereum/keystore
    entrypoint:
      - ash
      - -c
      - |
          IP=$$(dig +short bootnode)
          geth \
          --fast \
          --nodekeyhex $$NODE_KEY_HEX \
          --networkid $$NETWORK_ID \
          --bootnodes=enode://$$BOOTNODE_ENODE@$$IP:3031 \
          --password /private-net/files/password.txt \
          --unlock $$UNLOCKED_ACCOUNTS \
          --etherbase 0 \
          --rpc \
          --rpcport 8545 \
          --rpcaddr 0.0.0.0 \
          --rpccorsdomain "*"