version: '2'

# geth Private Network
# Start with: docker-compose up -d

services:
  bootnode: # Cannot be Scaled
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile.preBuilt
    image: geth-private-net
    ports:
      - "8545:8545"
    env_file: .env
    networks:
      geth-private:
        # Hard Coded Port for Static Node Connection
        ipv4_address: 172.19.0.2
    volumes: # Volume in the Password File
      - ./files/password.txt:/password.txt
    command: >
      --nodekeyhex $BOOTNODE_KEY_HEX 
      --password /password.txt
      --unlock $UNLOCKED_ACCOUNTS 
  miner: # Can be Scaled: docker-compose up --scale miner=5
    depends_on: 
      - bootnode
    image: geth-private-net
    ports:
      - "8545"
    env_file: .env
    networks:
      geth-private:
    command: >
      --mine 
      --minerthreads=1 
      --etherbase $ETHERBASE
  # node: # Can be Scaled: docker-compose up --scale node=5
  #   depends_on:
  #     - bootnode
  #   image: geth-private-net
  #   ports:
  #     - "8545"
  #   env_file: .env
  #   networks:
  #     geth-private:
         

networks:
  geth-private:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
