version: '2'

# geth Private Network
# Start with: docker-compose up -d

services:
  bootnode:
    build: 
      context: ..
      dockerfile: ./private-net/Dockerfile.preBuilt
    image: geth-private-net
    ports:
      - "8545:8545"
    env_file: .env
    networks:
      geth-private:
        ipv4_address: 172.19.0.2
    entrypoint:
      - ash
      - -c
      - |
        geth \
          --networkid $$NETWORK_ID \
          --password /private-net/files/password.txt \
          --unlock $$UNLOCKED_ACCOUNTS \
          --rpc \
          --rpccorsdomain "*" \
          --rpcaddr 0.0.0.0 \
          --rpcapi="eth,net,web3,personal" \
          --verbosity 9 \
          --nodekeyhex $$BOOTNODE_KEY_HEX 
  miner:
    depends_on: 
      - bootnode
    image: geth-private-net
    ports:
      - "8545"
    env_file: .env
    networks:
      geth-private:
        ipv4_address: 172.19.0.3
    entrypoint:
      - ash
      - -c
      - |
        geth \
          --networkid $$NETWORK_ID \
          --password /private-net/files/password.txt \
          --unlock $$UNLOCKED_ACCOUNTS \
          --rpc \
          --rpccorsdomain "*" \
          --rpcaddr 0.0.0.0 \
          --rpcapi="eth,net,web3,personal" \
          --mine \
          --minerthreads=1 \
          --etherbase $$ETHERBASE \
          --nodekeyhex $$MINER_KEY_HEX 
  node:
    depends_on:
      - bootnode
    image: geth-private-net
    ports:
      - "8545"
    env_file: .env
    networks:
      geth-private:
    entrypoint:
      - ash
      - -c
      - |
        geth \
          --networkid $$NETWORK_ID \
          --password /private-net/files/password.txt \
          --unlock $UNLOCKED_ACCOUNTS \
          --rpc \
          --rpccorsdomain "*" \
          --rpcaddr 0.0.0.0 \
          --rpcapi="eth,net,web3,personal"
         

networks:
  geth-private:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1

# For Reference:
# BOOTNODE_IP=$$(dig +short bootnode)
# --bootnodes=enode://$$BOOTNODE_ENODE@172.19.0.2:3030 \

# - |
#          geth \
#          --networkid $$NETWORK_ID \
#          --password /private-net/files/password.txt \
#          --unlock $$UNLOCKED_ACCOUNTS \
#          --rpcapi="eth,net,web3,personal" \
#          --rpccorsdomain "*" \
#          --rpcaddr 0.0.0.0 \
#          --rpc \
#          --mine \
#          --minerthreads=1 \
#          --etherbase $$ETHERBASE \
#          --nodekeyhex $$BOOTNODE_KEY_HEX dumpconfig > ~/config.toml